#!/bin/bash

#Prepare Host
hostnamectl set-hostname ovirt.example.local
host ovirt.example.local

#Update Host
sudo yum update -y
reboot

#Install required oVirt Packages as outlined in Mastering KVM Virtualization.
sudo dnf install qemu-kvm qemu-kvm-tools libvirt vdsm vdsm-cli spice-server

#Install oVirt Repo
yum install http://plain.resources.ovirt.org/pub/yum-repo/ovirt-release35.rpm
yum -y install ovirt-engine

#Start the libvirtd process which manages the qemu-kvm instance
sudo systemctl enable libvirtd && systemctl start libvirtd

#Add current user to the virtualization manger groups
sudo usermod -g $USER libvirt
groups

#Download CentOS version 7 and place it in the default pool location for qemu-kvm
sudo wget -O /var/lib/libvirt/images/CentOS-7-x86_64-Minimal-1908.iso "http://mirror.sjc02.svwh.net/centos/7.7.1908/isos/x86_64/CentOS-7-x86_64-Minimal-1908.iso"
